load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

android_sdk_repository(
    name = "androidsdk",
    path = "/usr/local/google/home/jingwen/sdk",
)

# Google Maven Repository
GMAVEN_TAG = "20181206-1"

http_archive(
    name = "gmaven_rules",
    strip_prefix = "gmaven_rules-%s" % GMAVEN_TAG,
    url = "https://github.com/bazelbuild/gmaven_rules/archive/%s.tar.gz" % GMAVEN_TAG,
)

load("@gmaven_rules//:gmaven.bzl", "gmaven_rules")

gmaven_rules()

maven_jar(
    name = "junit_junit",
    artifact = "junit:junit:4.12",
)

maven_jar(
    name = "javax_inject_javax_inject",
    artifact = "javax.inject:javax.inject:1",
)

maven_jar(
    name = "org_hamcrest_java_hamcrest",
    artifact = "org.hamcrest:java-hamcrest:2.0.0.0",
)

maven_jar(
    name = "com_google_inject_guice",
    artifact = "com.google.inject:guice:4.0",
)

ATS_RELEASE = "1.1.0-beta01"

http_archive(
    name = "android_test_support",
    sha256 = "2bbcc91195963d154cba1f062d958eb242d4a6a62cf7bb1e95823af8e351e504",
    strip_prefix = "android-test-androidx-test-%s" % ATS_RELEASE,
    urls = ["https://github.com/android/android-test/archive/androidx-test-%s.tar.gz" % ATS_RELEASE],
)

load("@android_test_support//:repo.bzl", "android_test_repositories")

android_test_repositories()
